import 'package:flutter/material.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({
    Key? key,
    required this.title,
  }) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
        Text(title),
      ],
    );
  }
}
